export const DEFAULT_LEFT_SIDEBAR_WIDTH = 288
export const DEFAULT_RIGHT_SIDEBAR_WIDTH = 420

export const LEFT_SIDEBAR_MIN_WIDTH = 240
export const LEFT_SIDEBAR_MAX_WIDTH = 420
export const RIGHT_SIDEBAR_MIN_WIDTH = 320
export const RIGHT_SIDEBAR_MAX_WIDTH = 620
export const SIDEBAR_COLLAPSE_DRAG_THRESHOLD = 72
export const SIDEBAR_COLLAPSE_DURATION_MS = 220

export const DEFAULT_CHAT_PROMPT_RATIO = 0.5
export const CHAT_PROMPT_MIN_RATIO = 0.2
export const CHAT_PROMPT_MAX_RATIO = 0.8
export const CHAT_PROMPT_AUTO_MAX_RATIO = 0.48
export const CHAT_EDITOR_ESTIMATED_LINE_HEIGHT = 22
export const CHAT_EDITOR_SECTION_CHROME_HEIGHT = 36
